name: Lint Code Base

on:
  push:
  pull_request:
  schedule:
    # Runs every day at 10:00 AM IST
    - cron: "30 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_JAVA: true
          DEFAULT_BRANCH: main
          CHECKSTYLE_CONFIG_FILE: .checkstyle.xml
